#pragma once
int lang;
enum promptName {
	//main()
	USE_GUI_QUERY,
	WINDOW_NAME,
	LOADING_LANG_INFO,
	SET_ZOOM_RATIO,
	ZOOM_RATIO_TOO_HIGH,
	ZOOM_RATIO_TOO_LOW,
	NOGUI_MAIN_MENU,
	NOGUI_WELCOME_MESSAGE,
	NOGUI_MAIN_MENU_TIP,
	NOGUI_OPTION_LOADIMG,
	NOGUI_OPTION_BINARIZE,
	NOGUI_OPTION_CONFIRMBINARIZE,
	NOGUI_OPTION_LOADIMGDATA,
	NOGUI_OPTION_MANUALREMOVALTOOL,
	NOGUI_OPTION_SCANCONNECTIVE,
	NOGUI_OPTION_SCANTEXTAREA,
	NOGUI_OPTION_PICKSAMPLE,
	NOGUI_OPTION_DORECOGNIZE,
	NOGUI_OPTION_EXIT,
	NOGUI_OPTION_ABOUT,
	NOGUI_MAIN_MENU_PROMPT_CHOOSE,
	GUI_MAIN_MENU,
	GUI_WELCOME_MESSAGE,
	GUI_MAIN_MENU_TIP,
	GUI_OPTION_LOADIMG,
	GUI_OPTION_BINARIZE,
	GUI_OPTION_CONFIRMBINARIZE,
	GUI_OPTION_LOADIMGDATA,
	GUI_OPTION_MANUALREMOVALTOOL,
	GUI_OPTION_SCANCONNECTIVE,
	GUI_OPTION_SCANTEXTAREA,
	GUI_OPTION_PICKSAMPLE,
	GUI_OPTION_DORECOGNIZE,
	GUI_OPTION_EXIT,
	GUI_OPTION_ABOUT,
	NOGUI_LOADIMG,
	NOGUI_LOADIMG_EXIT_PROMPT,
	NOGUI_LOADIMG_TIP,
	NOGUI_LOADIMG_INPUT_PROMPT,
	GUI_LOADIMG,
	GUI_LOADIMG_INPUT_PROMPT,
	GUI_BUTTON_CONFIRM,
	GUI_BUTTON_EXIT,
	NOGUI_LOADIMG_FAIL_LOADING,
	GUI_PROMPT_ERROR,
	GUI_LOADIMG_FAIL_LOADING,
	GUI_BUTTON_BACK,
	NOGUI_LOADIMG_TOOLARGE,
	GUI_LOADIMG_TOOLARGE,
	NOGUI_CLOSEWINDOW_PROMPT,
	GUI_CLOSEWINDOW_PROMPT,
	CV_LOADIMG_WINDOWNAME,
	NOGUI_LOADIMG_SUCCESS,
	NOGUI_LOADIMG_CONFIRMFILE,
	GUI_PROMPT_QUESTION,
	GUI_LOADIMG_SUCCESS,
	GUI_LOADIMG_CONFIRMFILE,
	GUI_BUTTON_YES,
	GUI_BUTTON_NO,
	NOGUI_BINARIZE,
	NOGUI_BINARIZE_PREVIOUS_STEP_REQUIRED,
	GUI_BINARIZE_PREVIOUS_STEP_REQUIRED,
	NOGUI_BINARIZE_TIP,
	GUI_BINARIZE,
	GUI_BINARIZE_TIP,
	CV_BINARIZE_WINDOWNAME,
	CV_BINARIZE_THRESHOLD
};
const std::string promptData0[] = {
	"Would you like to use GUI? 0 for no, others for yes: ",
	"Bill Statistics GUI", // Temporaily unused constant
	"Loading language pack...", // Not applicable for this language
	"Input zoom ratio, 1 for 100\%: ",
	"Zoom ratio too high, set to %d\%.\n",
	"Zoom ratio too low, set to 100\%.\n",
	"[Main Menu]\n",
	"Welcome to Bill Statistics Software! Choose what you want: \n",
	"* Tip: The IDs without [] should be done with the order they lists, while the one with it is optional to execute.\n",
	" 1. Load Image\n",
	" 2. Binarize the Image\n",
	" 3. Confirm Binarize\n",
	" 4. Load Image Data\n",
	"[5]. Manual Removal Tool\n",
	" 6. Scan Connective Area\n",
	" 7. Automatic Text Areas Detecting\n",
	" 8. Picking Samples\n",
	" 9. Do Recognize\n",
	" 99. Exit\n",
	" 999. About\n",
	"Your Choice: ",
	"Main Menu",
	"Welcome to Bill Statistics Software! Choose what you want.",
	"* Tip: The names without [] should be done with the order they lists, while the one with it is optional to execute.",
	"Load Image",	"Binarize the Image",	"Confirm Binarize",	"Load Image Data",	"[Manual Removal Tool]",	"Scan Connective Area",	"Automatic Text Areas Detecting",	"Picking Samples",	"Do Recognize",	"Exit",	"About",
	"[Load Image]\n",
	"Input exit to go back\n",
	"After the input of file path, the preview will be shown, you need to close the window by pressing Enter key in order to continue the operation.",
	"Input the RELATIVE path of the image: ",
	"Load Image",
	"Please input RELATIVE path of the image below:",
	"Confirm",
	"Exit",
	"Failed to load the image!",
	"Error",
	"Failed to load the image!",
	"Back",
	"The image is too large!",
	"The image is too large!",
	"Press Enter to confirm.",
	"Press Enter to confirm.",
	"Original Image",
	"Image loaded.\n",
	"Do you want to change a file? Y to confirm, others to not confirm: ",
	"Question",
	"Image loaded.",
	"Would you like to change a file?",
	"Yes",
	"No",
	"[Binarize Image]\n",
	"ERROR: ORIGINAL IMAGE NOT LOADED\n",
	"ERROR: ORIGINAL IMAGE NOT LOADED\n",
	"Scroll the bar to the position where best shows the information on your image and most of the other things were removed.\nPress Enter to confirm.\n",
	"Binarize Image",
	"Scroll the bar to the position where best shows the information on your image and most of the other things were removed.",
	"Binarized Image",
	"threshold"
};

const std::string promptData1[] = {
	"您希望使用图形界面吗？0 表示不使用，其他表示使用。 ",
	"智能账单统计器图形界面", // Temporaily unused constant
	"正在加载语言数据…",
	"输入缩放比例，1 表示 100\%： ",
	"缩放比例过高，已设为 %d\%",
	"缩放比例过低，已设为 100\%",
	"[主菜单]\n",
	"欢迎使用智能账单统计器，请选择您需要的功能:\n",
	"* 提示：不带 [] 的编号应该按顺序执行，而带有的选项是否执行是可选的。\n",
	" 1. 读取图像\n",
	" 2. 图像二值化\n",
	" 3. 确认二值化\n",
	" 4. 读取图像数据\n",
	"[5]. 手动移除工具\n",
	" 6. 检测联通块\n",
	" 7. 检测文字区域\n",
	" 8. 采样\n",
	" 9. 识别\n",
	" 99. 退出\n",
	" 999. 关于\n",
	"你的选择： ",
	u8"主菜单",
	u8"欢迎使用智能账单统计器，请选择您需要的功能。",
	u8"* 提示：名称不带 [] 应该按顺序执行，而带有的选项是否执行是可选的。",
	u8"读取图像",
	u8"图像二值化",
	u8"确认二值化",
	u8"读取图像数据",
	u8"手动移除工具",
	u8"检测联通块",
	u8"检测文字区域",
	u8"采样",
	u8"识别",
	u8"退出",
	u8"关于",
	"[读取图像]\n",
	"输入 exit 以返回\n",
	"在输入完路径后，将显示预览窗口，请按下 Enter 键以继续接下来的操作。\n",
	"输入文件的 相对 路径：",
	u8"读取图像",
	u8"请在下方输入文件的 相对 路径：",
	u8"确认",
	u8"退出",
	"图像读取失败！",
	u8"错误",
	u8"图像读取失败！",
	u8"返回",
	"图像过大！",
	u8"图像过大！",
	"按回车键以关闭窗口。",
	u8"按回车键以关闭窗口。",
	"原始图像",
	"图像已加载。\n",
	"您想要换一个文件吗？Y 表示更换，其他表示不更换。",
	u8"询问",
	u8"图像已加载。",
	u8"您想要换一个文件吗？",
	u8"是",
	u8"否",
	"[图像二值化]\n",
	"错误：图像未加载。\n",
	u8"错误：图像未加载。",
	"滑动选择器使得图像达到在重要信息得以保留前提下尽可能去除无用信息的状态。\n按回车以确认。\n",
	u8"图像二值化",
	"滑动选择器使得图像达到在重要信息得以保留前提下尽可能去除无用信息的状态。",
	"结果预览",
	"阈值"
};

const char* getPromptText(int promptID) {
	if (lang == 0)
		return promptData0[promptID].data();
	else if (lang == 1)
		return promptData1[promptID].data();
	else
		return promptData0[promptID].data();
}