//Copyright (c) ksyx 2019, all rights reserved. This software is under MIT license.
#pragma once
int lang;
enum promptName {
	//main()
	USE_GUI_QUERY,
	WINDOW_NAME,
	LOADING_LANG_INFO,
	SET_ZOOM_RATIO,
	ZOOM_RATIO_TOO_HIGH,
	ZOOM_RATIO_TOO_LOW,
	NOGUI_MAIN_MENU,
	NOGUI_WELCOME_MESSAGE,
	NOGUI_MAIN_MENU_TIP,
	NOGUI_OPTION_LOADIMG,
	NOGUI_OPTION_BINARIZE,
	NOGUI_OPTION_CONFIRMBINARIZE,
	NOGUI_OPTION_LOADIMGDATA,
	NOGUI_OPTION_MANUALREMOVALTOOL,
	NOGUI_OPTION_SCANCONNECTIVE,
	NOGUI_OPTION_SCANTEXTAREA,
	NOGUI_OPTION_PICKSAMPLE,
	NOGUI_OPTION_DORECOGNIZE,
	NOGUI_OPTION_EXPORT,
	NOGUI_OPTION_SAVESAMPLE,
	NOGUI_OPTION_LOADSAMPLE,
	NOGUI_OPTION_EXIT,
	NOGUI_OPTION_ABOUT,
	NOGUI_MAIN_MENU_PROMPT_CHOOSE,
	GUI_MAIN_MENU,
	GUI_WELCOME_MESSAGE,
	GUI_MAIN_MENU_TIP,
	GUI_OPTION_LOADIMG,
	GUI_OPTION_BINARIZE,
	GUI_OPTION_CONFIRMBINARIZE,
	GUI_OPTION_LOADIMGDATA,
	GUI_OPTION_MANUALREMOVALTOOL,
	GUI_OPTION_SCANCONNECTIVE,
	GUI_OPTION_SCANTEXTAREA,
	GUI_OPTION_PICKSAMPLE,
	GUI_OPTION_DORECOGNIZE,
	GUI_OPTION_EXPORT,
	GUI_OPTION_SAVESAMPLE,
	GUI_OPTION_LOADSAMPLE,
	GUI_OPTION_EXIT,
	GUI_OPTION_ABOUT,
	NOGUI_LOADIMG,
	NOGUI_LOADIMG_EXIT_PROMPT,
	NOGUI_LOADIMG_TIP,
	NOGUI_LOADIMG_INPUT_PROMPT,
	GUI_LOADIMG,
	GUI_LOADIMG_INPUT_PROMPT,
	GUI_BUTTON_CONFIRM,
	GUI_BUTTON_EXIT,
	NOGUI_LOADIMG_FAIL_LOADING,
	GUI_PROMPT_ERROR,
	GUI_LOADIMG_FAIL_LOADING,
	GUI_BUTTON_BACK,
	NOGUI_LOADIMG_TOOLARGE,
	GUI_LOADIMG_TOOLARGE,
	NOGUI_CLOSEWINDOW_PROMPT,
	GUI_CLOSEWINDOW_PROMPT,
	CV_LOADIMG_WINDOWNAME,
	NOGUI_LOADIMG_SUCCESS,
	NOGUI_LOADIMG_CONFIRMFILE,
	GUI_PROMPT_QUESTION,
	GUI_LOADIMG_SUCCESS,
	GUI_LOADIMG_CONFIRMFILE,
	GUI_BUTTON_YES,
	GUI_BUTTON_NO,
	NOGUI_BINARIZE,
	NOGUI_BINARIZE_PREVIOUS_STEP_REQUIRED,
	GUI_BINARIZE_PREVIOUS_STEP_REQUIRED,
	NOGUI_BINARIZE_TIP,
	GUI_BINARIZE,
	GUI_BINARIZE_TIP,
	CV_BINARIZE_WINDOWNAME,
	CV_BINARIZE_THRESHOLD,
	NOGUI_CONFIRMBINARIZE,
	NOGUI_CONFIRMBINARIZE_PREVIOUS_STEP_REQUIRED,
	GUI_CONFIRMBINARIZE_PREVIOUS_STEP_REQUIRED,
	NOGUI_CONFIRMBINARIZE_HAVE_BEEN_DONE,
	GUI_CONFIRMBINARIZE_HAVE_BEEN_DONE,
	NOGUI_CONFIRMBINARIZE_OPERATION_COMPLETE,
	GUI_PROMPT_INFO,
	GUI_CONFIRMBINARIZE_OPERATION_COMPLETE,
	NOGUI_LOADIMGDATA,
	NOGUI_LOADIMGDATA_PREVIOUS_STEP_REQUIRED,
	GUI_LOADIMGDATA_PREVIOUS_STEP_REQUIRED,
	NOGUI_LOADING,
	GUI_PROMPT_LOADING_CAPTION,
	GUI_PROMPT_LOADING_CONTENT,
	NOGUI_DONE,
	GUI_PROMPT_DONE,
	NOGUI_MANUALREMOVALTOOL,
	NOGUI_MANUALREMOVALTOOL_PREVIOUS_STEP_REQUIRED,
	GUI_MANUALREMOVALTOOL_PREVIOUS_STEP_REQUIRED,
	NOGUI_MANUALREMOVALTOOL_TIP,
	GUI_MANUALREMOVALTOOL,
	GUI_MANUALREMOVALTOOL_PURPOSETIP,
	GUI_MANUALREMOVALTOOL_BEHAVIORTIP,
	GUI_MANUALREMOVALTOOL_NOTICE,
	GUI_MANUALREMOVALTOOL_OPERATIONTIP,
	CV_MANUALREMOVALTOOL_WINDOWNAME,
	NOGUI_SCANCONNECTIVE,
	NOGUI_SCANCONNECTIVE_PREVIOUS_STEP_REQUIRED,
	GUI_SCANCONNECTIVE_PREVIOUS_STEP_REQUIRED,
	NOGUI_SCANCONNECTIVE_ALREADYDONE,
	GUI_SCANCONNECTIVE_ALREADYDONE,
	CV_SCANCONNECTIVE_WINDOWNAME,
	NOGUI_SCANCONNECTIVE_DONE,
	GUI_SCANCONNECTIVE,
	GUI_SCANCONNECTIVE_DONE,
	NOGUI_SCANTEXTAREA,
	NOGUI_SCANTEXTAREA_PREVIOUS_STEP_REQUIRED,
	GUI_SCANTEXTAREA_PREVIOUS_STEP_REQUIRED,
	NOGUI_SCANTEXTAREA_ALREADYDONE,
	GUI_SCANTEXTAREA_ALREADYDONE,
	CV_SCANTEXTAREA_WINDOWNAME,
	NOGUI_SCANTEXTAREA_PREPARING,
	GUI_SCANTEXTAREA_PREPARING,
	NOGUI_SCANTEXTAREA_WORKING,
	GUI_SCANTEXTAREA_WORKING,
	//GUI_SCANTEXTAREA_DONE=GUI_SCANCONNECTIVE_DONE,
	NOGUI_PICKSAMPLE,
	NOGUI_PICKSAMPLE_PREVIOUS_STEP_REQUIRED,
	GUI_PICKSAMPLE_PREVIOUS_STEP_REQUIRED,
	NOGUI_PICKSAMPLE_TIP_IMPORTANCE,
	NOGUI_PICKSAMPLE_TIP_OPERATION,
	NOGUI_PICKSAMPLE_TIP_COMPLETION,
	NOGUI_PICKSAMPLE_TIP_NOTICE,
	NOGUI_PICKSAMPLE_TIP_APPEARANCE,
	NOGUI_PICKSAMPLE_CURRENTITEM,
	GUI_PICKSAMPLE_GUIDE_CAPTION,
	GUI_PICKSAMPLE_TIP_IMPORTANCE,
	GUI_PICKSAMPLE_TIP_OPERATION,
	GUI_PICKSAMPLE_TIP_COMPLETION,
	GUI_PICKSAMPLE_TIP_TICE,
	GUI_PICKSAMPLE_TIP_APPEARANCE,
	GUI_PICKSAMPLE_CURRENTITEM,
	CV_PICKSAMPLE_IMAGE_WINDOWNAME,
	CV_PICKSAMPLE_SAMPLE_WINDOWNAME,
	NOGUI_DORECOGNIZE,
	NOGUI_DORECOGNIZE_PREVIOUS_STEP_REQUIRED,
	GUI_DORECOGNIZE_PREVIOUS_STEP_REQUIRED,
	NOGUI_DORECOGNIZE_GUIDE,
	NOGUI_DORECOGNIZE_RIGHTDOWN,
	NOGUI_DORECOGNIZE_LEFTUP,
	GUI_DORECOGNIZE,
	GUI_DORECOGNIZE_GUIDE,
	GUI_DORECOGNIZE_RIGHTDOWN,
	GUI_DORECOGNIZE_LEFTUP,
	CV_DORECOGNIZE_WINDOWNAME,
	NOGUI_DORECOGNIZE_INVAILDINPUT,
	GUI_DORECOGNIZE_INVAILDINPUT,
	NOGUI_DORECOGNIZE_ORIGINALENTRIES,
	NOGUI_DORECOGNIZE_SUMMARY,
	GUI_DORECOGNIZE_RESULT_CAPTION,
	GUI_DORECOGNIZE_ORIGINALENTRIES,
	GUI_DORECOGNIZE_SUMMARY,
	GUI_DORECOGNIZE_INCOME,
	GUI_DORECOGNIZE_OUTGOING,
	GUI_ABOUT,
	NOGUI_EXPORT,
	GUI_EXPORT,
	CV_EXPORT_WINDOWNAME,
	NOGUI_EXPORT_PROMPT_ENTRYNUM_INPUT,
	GUI_PROMPT_INPUT,
	GUI_EXPORT_PROMPT_ENTRYNUM_INPUT,
	NOGUI_EXPORT_INVAILDINPUT,
	GUI_EXPORT_INVAILDINPUT,
	NOGUI_EXPORT_DONE,
	GUI_EXPORT_DONE,
	NOGUI_SAVESAMPLE,
	GUI_SAVESAMPLE,
	NOGUI_LOADSAMPLE,
	GUI_LOADSAMPLE
};
const std::string promptData0[] = {
	"Would you like to use GUI? 0 for no, others for yes: ",
	"Bill Statistics GUI", // Temporaily unused constant
	"Loading language pack...", // Not applicable for this language
	"Input zoom ratio, 1 for 100\%: ",
	"Zoom ratio too high, set to %d\%.\n",
	"Zoom ratio too low, set to 100\%.\n",
	"[Main Menu]\n",
	"Welcome using the program! Choose what you want: \n",
	"* Tip: The IDs without [] should be done with the order they lists, while the one with it is optional to execute.\n",
	" 1. Load Image\n",
	" 2. Binarize the Image\n",
	" 3. Confirm Binarize\n",
	" 4. Load Image Data\n",
	"[5]. Manual Removal Tool\n",
	" 6. Scan Connective Area\n",
	" 7. Automatic Text Areas Detecting\n",
	" 8. Picking Samples\n",
	" 9. Do Recognize\n",
	" 10. Export Text Images\n",
	" 11. Save Samples\n",
	" 12. Load Samples",
	" 99. Exit\n",
	" 999. About\n",
	"Your Choice: ",
	"Main Menu",
	"Welcome using the program! Choose what you want.",
	"* Tip: The names without [] should be done with the order they lists, while the one with it is optional to execute.",
	"Load Image",
	"Binarize the Image",
	"Confirm Binarize",
	"Load Image Data",
	"[Manual Removal Tool]",
	"Scan Connective Area",
	"Automatic Text Areas Detecting",
	"Picking Samples",
	"Do Recognize",
	"[Export Text Images]",
	"[Save Samples]",
	"[Load Samples]",
	"Exit",
	"About",
	"[Load Image]\n",
	"Input exit to go back\n",
	"After the input of file path, the preview will be shown, you need to close the window by pressing Enter key in order to continue the operation.",
	"Input the RELATIVE path of the image: ",
	"Load Image",
	"Please input RELATIVE path of the image below:",
	"Confirm",
	"Exit",
	"Failed to load the image!",
	"Error",
	"Failed to load the image!",
	"Back",
	"The image is too large!",
	"The image is too large!",
	"Press Enter to confirm.",
	"Press Enter to confirm.",
	"Original Image",
	"Image loaded.\n",
	"Do you want to change a file? Y to confirm, others to not confirm: ",
	"Question",
	"Image loaded.",
	"Would you like to change a file?",
	"Yes",
	"No",
	"[Binarize Image]\n",
	"ERROR: ORIGINAL IMAGE NOT LOADED\n",
	"ERROR: ORIGINAL IMAGE NOT LOADED\n",
	"Scroll the bar to the position where best shows the information on your image and most of the other things were removed.\nPress Enter to confirm.\n",
	"Binarize Image",
	"Scroll the bar to the position where best shows the information on your image and most of the other things were removed.",
	"Binarized Image",
	"threshold",
	"[Confirm Binarize]\n",
	"ERROR: IMAGE NOT BINARIZED!\n",
	"Image not binarized.",
	"ERROR: THIS BINARIZE HAS BEEN CONFIRMED!\n",
	"This binarize has been confirmed.",
	"Confirmed.\n",
	"Info",
	"Confirmed.",
	"[Load Image Data]",
	"ERROR: BINARIZE NOT CONFIRMED!\n",
	"Binarize not confirmed.",
	"Loading, please wait.\n",
	"Work in progress",
	"Loading, please wait.",
	"Done.\n",
	"Done.",
	"[Manual Removal Tool]\n",
	"ERROR: IMAGE DATA NOT LOADED\n",
	"Image data not loaded.",
	"Use this tool to remove the unimportant details from the image, once you dobule right-clicked a point, all of the points that have a fully-black path to it will be removed.\nNOTE THAT THIS OPERATION CAN NOT BE UNDID EXCEPT RELOADING THE IMAGE.\n",
	"Manual Removal Tool",
	"Use this tool to remove the unimportant details from the image, once you dobule right-clicked a point, ",
	"all of the points that have a fully-black path to it will be removed.",
	"NOTICE THAT THIS OPERATION CAN NOT BE UNDID EXCEPT RELOADING THE IMAGE.",
	"Press Enter to close the window and complete the operation.",
	"Removal Tool",
	"[Scan Connective Area]\n",
	"ERROR: IMAGE DATA NOT LOADED\n",
	"Image data not loaded.",
	"Are you sure to calcuate the connective area AGAIN? Y to confirm, the others to not confirm.\n",
	"Are you sure to calcuate the connective area AGAIN?",
	"Connective Area Scanning",
	"Completed, please press Enter.\n",
	"Connective Area Scanning",
	"Completed, please press Enter.",
	"[Automatic Text Areas Detecting]\n",
	"ERROR: CONNECTIVE AREA NOT DETECTED\n",
	"Connective area not detected.",
	"Are you sure to detect text areas AGAIN? Y to confirm, the others to not confirm.\n",
	"Are you sure to detect text areas AGAIN?",
	"Automatic Text Areas Detecting",
	"Preparing for the operation...\n",
	"Preparing for the operation...",
	"Calculating Text Areas...\n",
	"Calculating Text Areas\n",
	"[Picking Samples]\n",
	"ERROR: TEXT AREA NOT DETECTED\n",
	"Text area not detected.",
	"The followings are important, read it if you are not familiar with the process.\n",
	"* Double left click on a black point to match sample and required information. If there is NO SUCH THING, double right-click on the image.\n",
	"* Press Enter to confirm your choice.\n",
	"Notice: once the window was closed, you can NOT go back, the ONLY way to change your choice is do the whole process again after completing all of the fetches THIS TIME.\n",
	"There will be a window showing your choice.\n",
	"Now Fetching: ",
	"Guide on fetching samples",
	"The followings are important, read it if you are not familiar with the process.",
	"* double left click on a black point to match sample and required information. If there is NO SUCH THING, double right-click on the image.",
	"* Press Enter to confirm your choice.",
	"Notice: once the window was closed, you can NOT go back, the ONLY way to change your choice is do the whole process again after completing all of the fetches THIS TIME.",
	"There will be a window showing your choice.",
	"Now Fetching: ",
	"Point Picking",
	"Current Choice",
	"[Do Recognize]\n",
	"ERROR: SAMPLE NOT FETCHED!\n",
	"Sample not fetched.",
	"Double left-click to choose point, now choose %s point. Double right-click to confirm.\n",
	"RIGHT-DOWN",
	"LEFT-UP",
	"Do Recognize",
	"Double left-click to choose point, now choose %s point. Double right-click to confirm.",
	"RIGHT-DOWN",
	"LEFT-UP",
	"Select Point",
	"ERROR: INVAILD RANGE\n",
	"Invaild range.",
	"Original Entries:\n",
	"Summary: income %.2lf | outgoing %.2lf\n",
	"Result",
	"Original Entries:",
	"Summary:",
	"Income %.2lf",
	"Outgoing %.2lf",
	"About",
	"[Export Text Images]\n",
	"Export Text Images",
	"Export Text Images",
	"Please input the number of entries in each data: ",
	"Input",
	"Please input the number of entries in each data.",
	"Invaild Input.\n",
	"Invaild Input.",
	"Operation done.\n",
	"Operation done. Click the button below to go back to main menu.",
	"[Save Samples]\n",
	"Save Samples",
	"[Load Samples]\n",
	"Load Samples"
};

const std::string promptData1[] = {
	"您希望使用图形界面吗？0 表示不使用，其他表示使用。 ",
	"Bill Statistics GUI", // Temporaily unused constant
	"正在加载语言数据…",
	"输入缩放比例，1 表示 100\%： ",
	"缩放比例过高，已设为 %d\%",
	"缩放比例过低，已设为 100\%",
	"[主菜单]\n",
	"欢迎使用本软件，请选择您需要的功能:\n",
	"* 提示：不带 [] 的编号应该按顺序执行，而带有的选项是否执行是可选的。\n",
	" 1. 读取图像\n",
	" 2. 图像二值化\n",
	" 3. 确认二值化\n",
	" 4. 读取图像数据\n",
	"[5]. 手动移除工具\n",
	" 6. 检测联通块\n",
	" 7. 检测文字区域\n",
	" 8. 采样\n",
	" 9. 识别\n",
	"[10]. 导出文本图像\n",
	"[11]. 储存采样数据\n",
	"[12]. 读取采样数据\n",
	" 99. 退出\n",
	" 999. 关于\n",
	"你的选择： ",
	u8"主菜单",
	u8"欢迎使用本软件，请选择您需要的功能。",
	u8"* 提示：名称不带 [] 应该按顺序执行，而带有的选项是否执行是可选的。",
	u8"读取图像",
	u8"图像二值化",
	u8"确认二值化",
	u8"读取图像数据",
	u8"[手动移除工具]",
	u8"检测联通块",
	u8"检测文字区域",
	u8"采样",
	u8"识别",
	u8"[导出文本图像]",
	u8"[储存采样数据]",
	u8"[读取采样数据]",
	u8"退出",
	u8"关于",
	"[读取图像]\n",
	"输入 exit 以返回\n",
	"在输入完路径后，将显示预览窗口，请按下 Enter 键以继续接下来的操作。\n",
	"输入文件的 相对 路径：",
	u8"读取图像",
	u8"请在下方输入文件的 相对 路径：",
	u8"确认",
	u8"退出",
	"图像读取失败！",
	u8"错误",
	u8"图像读取失败！",
	u8"返回",
	"图像过大！",
	u8"图像过大！",
	"按回车键以关闭窗口。",
	u8"按回车键以关闭窗口。",
	"原始图像",
	"图像已加载。\n",
	"您想要换一个文件吗？Y 表示更换，其他表示不更换。",
	u8"询问",
	u8"图像已加载。",
	u8"您想要换一个文件吗？",
	u8"是",
	u8"否",
	"[图像二值化]\n",
	"错误：图像未加载。\n",
	u8"图像未加载。",
	"滑动选择器使得图像达到在重要信息得以保留前提下尽可能去除无用信息的状态。\n按回车以确认。\n",
	u8"图像二值化",
	u8"滑动选择器使得图像达到在重要信息得以保留前提下尽可能去除无用信息的状态。",
	"结果预览",
	"阈值",
	"[确认二值化]\n",
	"错误：图像尚未二值化！\n",
	u8"图像尚未二值化。",
	"错误：此次二值化已确认。\n",
	u8"此次二值化已确认。",
	"已确认。\n",
	u8"信息",
	u8"已确认",
	"[读取图像信息]",
	"错误：二值化尚未确认！\n",
	u8"二值化尚未确认。",
	"加载中，请稍候。\n",
	u8"处理中",
	u8"加载中，请稍候。",
	"已完成。\n",
	u8"已完成。",
	"[手动移除工具]\n",
	"错误：图像数据未加载！\n",
	u8"图像数据未加载。",
	"使用本工具来移除图像中的无关信息, 一旦您右键双击一个点, 所有与其之间存在一条全为黑色像素路径的点将被移除。\n注意！除了重新加载图像，本操作不可逆！\n",
	u8"手动移除工具",
	u8"使用本工具来移除图像中的无关信息，一旦您双击一个点，",
	u8"所有与其之间存在一条全为黑色像素的点将被移除。",
	u8"注意！除了重新加载图像，本操作不可逆！",
	u8"按回车键以关闭窗口，并完成操作。",
	"移除工具",
	"[扫描联通块]\n",
	"错误：图像数据未加载！\n",
	u8"图像数据未加载。",
	"您想要重新计算联通块吗？输入 Y 确认，输入其他内容退出。\n",
	u8"您想要重新计算联通块吗？",
	"联通块检测",
	"已完成，请按回车键确认。\n",
	u8"扫描联通块",
	u8"已完成。请按回车键继续。",
	"[自动文字区域检测]\n",
	"错误：联通块尚未检测。n",
	u8"联通块尚未检测。",
	"您确认要重新检测文字区域吗？输入 Y 以确认，输入其他以退出。\n",
	u8"您确定要重新检测文字区域吗？",
	"自动文字区域检测",
	"正在为该操作进行准备工作…\n",
	u8"正在为该操作进行准备工作…",
	"计算文字区域中…\n",
	u8"计算文字区域中…",
	"[采样]\n",
	"错误：文字区域尚未检测！\n",
	u8"文字区域尚未检测。",
	"以下内容很重要，如果您不熟悉操作，请仔细阅读。\n",
	"* 左键双击一个点来建立当前采样内容和图像间的联系。如果不存在当前字符，请右键双击图像。\n",
	"* 按下回车键确认您的选择。\n",
	"注意：一旦窗口关闭，您将无法回到之前的字符，唯一的修正方式是在完成本次取样后再次进行操作以覆盖先前操作。\n",
	"屏幕上将显示您的选择。\n",
	"当前正在对该字符进行采样：",
	u8"采样指导",
	u8"以下内容很重要，如果您不熟悉操作，请仔细阅读。",
	u8"* 左键双击一个点来建立当前采样内容和图像间的联系。如果不存在当前字符，请右键双击图像。",
	u8"* 按下回车键确认您的选择。",
	u8"注意：一旦窗口关闭，您将无法回到之前的字符，唯一的修正方式是在完成本次取样后再次进行操作以覆盖先前操作。",
	u8"屏幕上将显示您的选择。",
	u8"当前正在对该字符进行采样：",
	"采样窗口",
	"当前选择",
	"[识别]\n",
	"错误：尚未采样！\n",
	u8"尚未采样。",
	"双击左键以选择 %s 的点，双击右键以确认。\n",
	"右下角",
	"左上角",
	u8"识别",
	u8"双击左键以选择 %s 的点，双击右键以确认。",
	u8"右下角",
	u8"左上角",
	"选择点",
	"错误：无效范围！\n",
	u8"无效范围。",
	"原始数据：\n",
	"小结: 收入 %.2lf | 支出 %.2lf\n",
	u8"结果",
	u8"原始数据:",
	u8"小结",
	u8"收入 %.2lf",
	u8"支出 %.2lf",
	u8"关于",
	"[导出文本图像]\n",
	u8"导出文本图像",
	"导出文本图像",
	"请输入各项中数据数：",
	u8"输入",
	u8"请输入各项中数据数。",
	"无效输入。",
	u8"无效输入。",
	"操作完成。",
	u8"操作完成，请点击下方按钮返回主菜单。",
	"[存储样本数据]\n",
	u8"存储样本数据",
	"[读取样本数据]\n",
	u8"读取样本数据"
};

const char* getPromptText(int promptID) {
	if (lang == 0)
		return promptData0[promptID].data();
	else if (lang == 1)
		return promptData1[promptID].data();
	else
		return promptData0[promptID].data();
}